### ISSUE TITLE
Prepare for OCaml 4.08

### ISSUE THREAD

**Issue by MattWindsor91** [MattWindsor91/act#100]
OCaml 4.08 is now in release candidate stage, which means that we should think about getting act (and its dependencies, such as travesty) ready to migrate over.

(Yay, 100th issue :tada:)

**Comment by MattWindsor91** [comment]
We can't do anything until either [ppx_tools](https://github.com/ocaml-ppx/ppx_tools) releases 4.08 support, or [ppx_deriving](https://github.com/ocaml-ppx/ppx_deriving) drops the dependency on it.  Backburner'd.

**Comment by johnwickerson** [comment]
This one smells like something only worth doing after the prototyping stage.

**Comment by MattWindsor91** [comment]
`ppx_deriving` recently updated to support 4.08, so I had a quick look to see whether we could move up without any effort.  Alas, no:

- `ppx_import` doesn't support 4.08;
- neither does `ppx_deriving_yojson`;
- changes in the various packages that have recently moved to 4.08 have now broken `clangml`, which doesn't affect ACT _yet_ but will if we change to using it for fuzzing/C manipulation;
- and homebrew doesn't track 4.08 because `camlp4` and `camlp5` _still_ don't support 4.08.

To say that `4.08` is a minor version increment from `4.07`, it's sure managed to be a major sticking point!  (Probably because of things manually targeting a single version of the AST, but still).

**Comment by MattWindsor91** [comment]
Seems to work on 4.08 now, so I'ma close
