### ISSUE TITLE
Investigate better names for `sim[ulator]`

### ISSUE THREAD

**Issue by MattWindsor91** [MattWindsor91/act#104]
A lot of bits of ACT refer to tools like herd7, litmus7, etc. as 'simulators' (or 'sims' for short).  This is a fairly catch-all and easy to say term, but it's misleading, because not all such tools simulate litmus tests (indeed. litmus7 runs them on actual hardware).

Better name suggestions welcome!

**Comment by johnwickerson** [comment]
Executor? Runner? Discoverer-of-allowable-final-states?!

**Comment by MattWindsor91** [comment]
Hmm.  Executor would be a good name for things like litmus7, but then I’m not sure it covers herd7, and I’m trying to get one concept for both of them 😂 

I just thought maybe ‘backend’ or ‘driver’, actually; that’s sufficiently nondescript to cover both bases.  Only problem is that it then rules out the possibility of ACT having any _other_ types of backend (and you could already argue that compilers are a form of ACT backend)!

**Comment by MattWindsor91** [comment]
ACT now refers to these as 'backend', so this issue is closed (but 'backend' is still a slightly eh name, so suggestions are still open)
