### ISSUE TITLE
Dependency on gawk needs making explicit

### ISSUE THREAD

**Issue by johnwickerson** [MattWindsor91/act#120]
Otherwise I get:

    env: gawk: No such file or directory

Fix seems to be

    brew install gawk

**Comment by MattWindsor91** [comment]
In the object-file-support branch, I've sidestepped around the need for `gawk` by making the splicing script explicitly require a marker to tell it when the input-to-splice has ended and the actual litmus harness has begun.  Slightly messy, but it saves a dependency!
